[package]
name = "test-1"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.15.0", features = ["train", "wgpu", "vision"] }
csv = "1.3.1"
serde = { version = "1.0.216", features = ["derive"] }
