[package]
name = "ui_frames"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.16.0", default-features = false }
iced = { version = "0.13.1", features = ["image"] }
model-training = { path = "../model-training" }
