[package]
name = "recorder"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
fs_extra = "1.3.0"
rdev = "0.5.3"
serde = { version = "1.0.217", features = ["derive"] }
xcap = "0.4.0"
common = {path = "../common"}